- src/main/java/com/mongodb/jdbc/MongoStatement.java
If we set batchSize to zero on an AggregateIterable, the cursor will not return any results. Instead of unconditionally setting batchSize to fetchSize, we should do so only when it's non-zero.
> SQL-152: Fix empty-batch bug when fetchSize is zero

- src/main/java/com/mongodb/jdbc/Column.java
- src/main/java/com/mongodb/jdbc/MongoDatabaseMetaData.java
- src/main/java/com/mongodb/jdbc/MongoResultDoc.java
- src/main/java/com/mongodb/jdbc/MongoResultSet.java
- src/main/java/com/mongodb/jdbc/MongoResultSetMetaData.java
- src/main/java/com/mongodb/jdbc/MongoStatement.java
- src/test/java/com/mongodb/jdbc/MongoMock.java
- src/test/java/com/mongodb/jdbc/MongoResultSetMetaDataTest.java
- src/test/java/com/mongodb/jdbc/MongoResultSetTest.java
- src/test/java/com/mongodb/jdbc/MongoStatementTest.java
This PR updates the JDBC driver to use $sql formatVersion 2.
> SQL-156: Use $sql formatVersion 2

- src/main/java/com/mongodb/jdbc/MongoDriver.java
- src/main/java/com/mongodb/jdbc/MongoFunction.java
- src/main/java/com/mongodb/jdbc/MongoJsonSchema.java
- src/main/java/com/mongodb/jdbc/MongoJsonSchemaResult.java
- src/main/java/com/mongodb/jdbc/MongoVersionedJsonSchema.java
Check me on the `MongoJsonSchemaResult`, the goal there is for that to be the deserialization type for the return type of `sqlGetResultSchema`
We aren't going to return a superdocument with `$jsonSchema`, right?
> SQL-513: Add MongoJsonSchema and MongoJsonSchemaResult

- resources/run_adl.sh
JIRA: https://jira.mongodb.org/browse/SQL-758
> SQL-758: Updating run_adl.sh to use golang 1.17

- src/main/java/com/mongodb/jdbc/MongoDatabaseMetaData.java
- src/main/java/com/mongodb/jdbc/MongoDriver.java
JIRA: https://jira.mongodb.org/browse/SQL-762
> SQL-762: Updating product and driver name

- .evg.yml
- src/main/java/com/mongodb/jdbc/BsonTypeInfo.java
- src/main/java/com/mongodb/jdbc/MongoJsonSchema.java
Wanted to familiarize myself a bit more with Gradle/groovy before working on SQL-504, so decided to do this one as a quick win
> SQL-765: Run spotlessCheck in an evergreen task

- .evg.yml
- build.gradle
Disabled TDVT and MySQLIntegrationTest but kept the code in for now.
Will remove the code when Mysql dialect is removed.
> SQL-761: Disable Mysql dialect related tests

- .evg.yml
- resources/integration_test/testdata/integration.yml
- resources/integration_test/tests/dbmd_variable_result_sets_data_methods.yml
- src/integration-test/java/com/mongodb/jdbc/integration/testharness/DataLoader.java
- src/integration-test/java/com/mongodb/jdbc/integration/testharness/IntegrationTestUtils.java
- src/integration-test/java/com/mongodb/jdbc/integration/testharness/models/TestDataEntry.java
Enable and add expected result sets which should have been done as part of SQL-668.
> SQL-789 : Enable and populate tests

- resources/run_adl.sh
Tested on `windows-vsCurrent-small` and `windows-64-vs2019-small` with the cygwin shell.
> SQL-974: Support running local ADF instance on Windows

- build.gradle
- gradle.properties
- resources/run_adl.sh
- src/integration-test/java/com/mongodb/jdbc/integration/testharness/DataLoader.java
- src/main/java/com/mongodb/jdbc/BsonExplicitCursor.java
* Also update Guava
* Replace use of legacy API with equivalent
> Update to 4.7.1 MongoDB driver

- src/main/java/com/mongodb/jdbc/MongoDatabaseMetaData.java
- src/test/java/com/mongodb/jdbc/MongoDatabaseMetaDataTest.java
Now filtering the admin database out of results, and I refactored to test the filter.
> SQL-1452: filter admin database from database results

- README.md
Additional documentation of the driver class name for clarity.
> SQL-1659: add one-liner mentioning class name to readme

- .evg.yml
I missed variables due to checking the wrong log. Additionally, even though the local testing variables aren't really sensitive I've made that function silent as well for good measure.
> SQL-1881: make functions silent that use sensitive vars

- .evg.yml
> SQL-2105: Trace artifacts after publish-maven on the same task 

- src/main/java/com/mongodb/jdbc/logging/MongoLogger.java
Found a very simple work-around!
> SQL_2142 : Driver not working under JBoss Log Manager / Quarkus

- resources/run_adf.sh
Applying the fix to clear the git global configuration made in the powerbi and odbc repos.
> SQL-2299: Clear git config settings related to url

- docs/overview.md
Specifically not going the route of how to use a local jar in a local project since we're focusing on tool users.
> SQL-2385: JDBC documentation

- .evg.yml
- evergreen/make_docs.sh
Making docs! https://spruce.mongodb.com/task/mongo_jdbc_driver_eap_release_make_docs_patch_5b24dc527da89971c1d713609a3b8bb12beec1f8_672a538144a808000739cf7f_24_11_05_17_19_09/files?execution=0
> SQL-2387: upload jdbc docs

- src/integration-test/java/com/mongodb/jdbc/integration/DCIntegrationTest.java
- src/main/java/com/mongodb/jdbc/MongoDriver.java
This change is cherry picked from the `on-prem-eap` branch to `master`.
> SQL-2514: Report authentication failure and expected SQLSTATE 

- gradle.properties
> upgrade driver version to 5.3.+

- .evg.yml
So we can figure out what's going on here.
> set silent to false for testing purposes

- .evg.yml
- print_it.py
In my testing these were the minimal changes to make the gradle task not fail, so here's hoping.
I also set silent back to true for the task.
> SQL-2489: New public signing key

- .evg.yml
- gradle/publish.sh
Here's the changes we worked on.
> Quotes for vars

- .evg.yml
- gradle/publish.sh
Not ideal but we need to see what's going on.
> have to debug this

- .evg.yml
- README.md
- gradle/publish.sh
This is a small one, only one reviewer needed imo. You've been helping with it so tagging you in @bucaojit
> update public key and set shell

- .evg.yml
Silkbomb 2.0 introduces the augment command which will allow you to upload your sbom to be scanned by OSV and have an augmented SBOM returned with any vulnerabilities in a single step.
Let me know if I'm missing anything or if there is anything else that can be cleaned up or improved. Thanks!
> update to silkbomb 2.0

- src/main/java/com/mongodb/jdbc/oidc/OidcAuthFlow.java
Cherry-Picked from `on-prem-eap` branch
> SQL-2506: Update browser invocation method for different platforms 

- .evg.yml
- gradle/deploy.gradle
- src/main/java/com/mongodb/jdbc/MongoConnection.java
- src/main/java/com/mongodb/jdbc/logging/MongoLogger.java
I added a check task to verify the javadoc can be generated so that we can avoid this issue going forward.
> SQL-2538: Javadoc fixes

- docs/overview.md
copy of content added to odbc overview
> Doc update

- src/main/java/com/mongodb/jdbc/MongoDriver.java
- src/test/java/com/mongodb/jdbc/MongoDriverTest.java
This disables the client cache. Do not use this with OIDC human flow :joy:
> SQL-2847: Add option to disable Client Cache
