mongodb/mongo-jdbc-driver

src/main/java/com/mongodb/jdbc/MongoResultSet.java, src/test/java/com/mongodb/jdbc/MongoResultSetTest.java
DBeaver was failing because it was calling `getObject` on LONGVARCHAR columns (not sure why it didn't use `getString`, but that's beside the point). This PR provides an implementation for `getObject`
=> SQL-153: Create basic getObject implementation

build.gradle, src/main/java/com/mongodb/jdbc/MongoConnection.java, src/main/java/com/mongodb/jdbc/MongoDriver.java
This PR adds the driver name and version (major.minor) to the client metadata.  
Obtained from `getClass().getPackage().getImplementationTitle()` and `getClass().getPackage().getImplementationVersion()`, otherwise defaults to 'mongodb-jdbc' and 0.0.
Log from ADL:
```
"clientMetadata": {"driver":{"name":"mongo-java-driver|sync|mongodb-jdbc","version":"3.12.10|1.0"} ...
```
=> SQL-447: Set client metadata in JDBC driver

src/main/java/com/mongodb/jdbc/MongoConnection.java, src/test/java/com/mongodb/jdbc/MongoConnectionTest.java
This PR modifies the `getAutoCommit()` to always return false. 
Modifies `setAutoCommit()` to throw SQLFeatureNotSupportedException if input parameter is set to `true`, no-op in case of `false`.
=> SQL-213: Rationalize get/setAutoCommit behavior

src/integration-test/java/com/mongodb/jdbc/integration/IntegrationTest.java, src/tdvt/java/com/mongodb/jdbc/tdvt/TDVTTest.java
JIRA: https://jira.mongodb.org/browse/SQL-480
Created ticket to address fixing and reenabling tests, added notes on a few of the test failures: 
https://jira.mongodb.org/browse/SQL-539
Disabled tests with @Ignore annotation when executeQuery was failing
Disabled by commenting failing asserts when other passing asserts are in test
=> SQL-480: Disabled failing integration and tdvt tests

src/integration-test/java/com/mongodb/jdbc/integration/MongoSQLIntegrationTest.java, src/integration-test/java/com/mongodb/jdbc/integration/testharness/TestGenerator.java, src/integration-test/java/com/mongodb/jdbc/integration/testharness/models/TestEntry.java
This PR updates the `TestEntry` model to include the `db` keyword and updates the integration test and data loader codepaths to use that test-defined db when establishing a connection.
=> SQL-563: Update integration tests and data loader to use db defined per test

resources/integration_test/tests/dbmd_variable_result_sets_data_methods.yml, src/main/java/com/mongodb/jdbc/MongoDatabaseMetaData.java, src/main/java/com/mongodb/jdbc/MongoSQLDatabaseMetaData.java
JIRA: https://jira.mongodb.org/browse/SQL-721
When tableNamePattern is null then table name will not be used to narrow the search.  Added test for getTables with tableNamePattern as `null`.
=> SQL-721: Handle null value in getTables() for tableNamePattern

src/main/java/com/mongodb/jdbc/MongoConnection.java, src/main/java/com/mongodb/jdbc/MongoDriver.java, src/main/java/com/mongodb/jdbc/MongoVersionedJsonSchema.java, src/test/java/com/mongodb/jdbc/MongoDriverTest.java
This patch just changes the visibility of `validateConn` to package level and calls it after creating a connection.
=> SQL-589: Use validateConn after connecting

src/main/java/com/mongodb/jdbc/MongoDriver.java, src/test/java/com/mongodb/jdbc/MongoDriverTest.java
As discussed in standup today, a small change to switch the default dialect from "mysql" to "mongosql"
=> SQL-774: Use the MongoSQL dialect by default

src/main/java/com/mongodb/jdbc/JsonSchema.java, src/main/java/com/mongodb/jdbc/MongoJsonSchema.java, src/test/java/com/mongodb/jdbc/MongoSQLMock.java, src/test/resources/mongoJsonSchemaTest/expectedOutput/flattenedAnyOfReducedToOneType.json, src/test/resources/mongoJsonSchemaTest/expectedOutput/polymorphicAdditionalProperties.json, src/test/resources/mongoJsonSchemaTest/expectedOutput/polymorphicItems.json, src/test/resources/mongoJsonSchemaTest/expectedOutput/simpleSchema.json, src/test/resources/mongoJsonSchemaTest/input/polymorphicAdditionalProperties.json, src/test/resources/mongoJsonSchemaTest/input/polymorphicItems.json
Transform "items" field values to a set of MongoJsonSchema and "additionalProperties" to a boolean value.
@rychipman, @bucaojit :  It seems that "items" is only used to know if isAny should return true or false. And, even there, the only information used is whether "items" is null or not.
I am not sure if we need to convert "items" to a set of MongoJsonSchema or if we could not simply convert it to a boolean value (tracking if items is null or not) and use the boolean value in isAny.
=> SQL-775: Handle all JsonSchema polymorphic fields

resources/integration_test/testdata/integration.yml, resources/integration_test/tests/query.yaml, src/integration-test/java/com/mongodb/jdbc/integration/testharness/IntegrationTestUtils.java, src/main/java/com/mongodb/jdbc/MongoSQLResultSet.java, src/main/java/com/mongodb/jdbc/NoCheckStateJsonWriter.java
JIRA: https://jira.mongodb.org/browse/SQL-800
getString() for Document and Array columns return extJSON string.
Added array value to the row in `types_other` collection.   Added integration test to query array and document values as string.
=> SQL-800: Implemented getString for Document and Array columns

.evg.yml, RELEASE.md, settings.gradle, smoketest/build.gradle, smoketest/src/main/java/com/mongodb/jdbc/smoketest/SmokeTest.java, smoketest/src/test/java/com/mongodb/jdbc/smoketest/SmokeTest.java
JIRA: https://jira.mongodb.org/browse/SQL-791
Added a smoke test that will block the publish-maven task if it fails.
Starts a local ADL to connect to, retrieve metadata, and run a query.
Smoke test uses the built shadowJar  `mongodb-jdbc-'+getReleaseVersion()+'-all.jar` as its dependency.
=> SQL-791: Adding smoke test for built artifacts

src/main/java/com/mongodb/jdbc/MongoConnection.java, src/main/java/com/mongodb/jdbc/MongoDriver.java, src/test/java/com/mongodb/jdbc/MongoDriverTest.java
Timeout errors were not propagated properly and the connection validation was incorrectly successful leading to unclear errors when executing queries.
=> SQL-876: Propagate timeout from connection validation

resources/integration_test/tests/dbmd_variable_result_sets_index_methods.yml, resources/integration_test/tests/query.yaml
Reenabled the skipped tests for tickets that have been fixed: SQL-659, SQL-668.
One question, MHOUSE-1459 is closed as won't fix.  The returned result set is empty.  I was debating whether to remove the skip reason and return the empty result set as that is the expected behavior now or keep skipped?
EDIT: Checked with Natacha about MHOUSE-1459 and will keep the tests skipped.
=> SQL-900: Reenable skipped JDBC integration tests

src/main/java/com/mongodb/jdbc/MongoResultSet.java, src/test/java/com/mongodb/jdbc/MongoSQLStatementTest.java
A simple fix I had shelved for a long time now.
=> SQL-916: ResultSet.close fails when calling Statement.close if Statement.closeOnClompetion is true

src/main/java/com/mongodb/jdbc/MongoSQLDatabaseMetaData.java
Replace the following repeated calls with the corresponding class-level constants
- `new BsonInt32(0)` -> `BSON_ZERO_INT_VALUE`
- `new BsonInt32(typeSearchable)` -> `BSON_TYPE_SEARCHABLE_INT_VALUE`
- `new BsonInt32(Types.OTHER)` -> `BSON_OTHER_INT_VALUE`
- `new BsonInt32(ResultSetMetaData.columnNullable)` -> `BSON_COLUMN_NULLABLE_INT_VALUE `
- `new BsonBoolean(false)` -> `BsonBoolean.FALSE`
- `new BsonNull()` -> `BsonNull.VALUE`
- `new BsonString("")` -> `BSON_EMPTY_STR_VALUE`
- `new BsonString("YES")` -> `BSON_YES_STR_VALUE`
- `new BsonString("NO")` -> `BSON_NO_STR_VALUE`
=> SQL-579: Refactor repeated new calls to class-level constants in MongoSQLDatabaseMetadata

src/main/java/com/mongodb/jdbc/MongoDatabaseMetaData.java, src/test/java/com/mongodb/jdbc/MongoDatabaseMetaDataTest.java
In the `toJavaPattern` method: 
- modified function to NOT replace escaped `_` or `%`
- escaped Java regex characters not escaped in SQL regex patterns 
- these characters were taken from the BI connector: `.^$*+?(){}|[]\\`
Additionally, I created unit tests for these changes.
=> SQL-567: Improve SQL-to-Java regex pattern method in MongoDatabaseMetaData class

resources/integration_test/tests/dbmd_constant_result_sets.yml, src/main/java/com/mongodb/jdbc/MongoSQLDatabaseMetaData.java
I changed the ordering of the result set to be ordered by DATA_TYPE (from least to greatest) if the DATA_TYPE is not equal to 1111. Additionally, I sorted all the Types with DATA_TYPE == 1111 alphabetically and put them after the types with DATA_TYPE != 1111.
=> SQL-707: Update getTypeInfo() result set to be ordered according to the specification

resources/run_adl.sh, src/main/java/com/mongodb/jdbc/BsonTypeInfo.java, src/main/java/com/mongodb/jdbc/MongoResultSet.java, src/test/java/com/mongodb/jdbc/BsonTypeInfoTest.java
This refactors `MongoResultSet` to use `BsonTypeInfo` and significantly cleans up the switch statements.
I've also removed the "end_of_document" check from `MongoResultSet` as it wasn't used in any meaningful way other than it couldn't be converted in any of the switches. Since it was a BsonValue that is being passed into the various conversion methods, there's actually no way for it to be an "end_of_document" since it can't be created as a concrete type to derive a `BsonType` from (let alone a `BsonTypeInfo`).
This also updates the go version used in the build task, addressing SQL-1083.
=> SQL-645: refactor MongoResultSet to use BsonTypeInfo

gradle.properties, src/main/java/com/mongodb/jdbc/MongoDriver.java
This is a quick driveby on two tickets worth doing a patch release for. The release will also enable ADF to run tests again using the JDBC driver, hopefully giving a lot more warning about breaking changes that may impact us.
=> SQL-1534 & SQL-1523: improve error message and upgrade driver

.evg.yml
There was an errant space in our evergreen file that prevented the download-center-update task from being seen and running
=> fix formatting

gradle.properties
This PR bumps the java driver version to 4.11.1. The release notes don't include anything that looks relevant for us, so this is just a one-liner bumping up the version.
=> SQL-1779: Update java driver version to 4.11.1

resources/integration_test/tests/query.yaml, src/main/java/com/mongodb/jdbc/MongoDatabaseMetaData.java, src/main/java/com/mongodb/jdbc/MongoJsonSchemaResult.java, src/main/java/com/mongodb/jdbc/MongoResultSet.java, src/main/java/com/mongodb/jdbc/MongoResultSetMetaData.java, src/main/java/com/mongodb/jdbc/MongoStatement.java, src/test/java/com/mongodb/jdbc/MongoResultSetMetaDataTest.java, src/test/java/com/mongodb/jdbc/MongoResultSetTest.java
To test, ran the SQL-1773 version of mongosql locally in ADF. tried each of unit tests and integration tests. Failing tests are the two result set tests expecting alphabetical order but getting select order
=> SQL-1707: put result set in select list order

src/main/java/com/mongodb/jdbc/MongoConnection.java, src/main/java/com/mongodb/jdbc/MongoDriver.java, src/main/java/com/mongodb/jdbc/logging/MongoSimpleFormatter.java, src/main/resources/logging.properties
MongoDriver used to reset the log manager configuration with the configuration of the logging.properties from inside our jar. This is problematic for other applications using JUL as their configuration is deleted.
Instead, we now do the configuration for our Filehandler programmatically.
=> SQL-1835:  The driver disables all logger when connecting

build.gradle, gradle.properties, resources/integration_test/tests/query.yaml, src/integration-test/java/com/mongodb/jdbc/integration/testharness/DataLoader.java, src/integration-test/java/com/mongodb/jdbc/integration/testharness/IntegrationTestUtils.java, src/integration-test/java/com/mongodb/jdbc/integration/testharness/models/TestEntry.java, src/main/java/com/mongodb/jdbc/MongoResultSet.java, src/main/java/com/mongodb/jdbc/MongoResultSetMetaData.java, src/test/java/com/mongodb/jdbc/MongoMock.java, src/test/java/com/mongodb/jdbc/MongoResultSetMetaDataTest.java, src/test/java/com/mongodb/jdbc/MongoResultSetTest.java, src/test/java/com/mongodb/jdbc/MongoStatementTest.java
In order to not break the existing behavior (and to match MySQL and Postgres), I did not rename the columns. 
Instead, the driver will fail retrieving information by column name if there is more than one column with the requested name.
=> SQL-1916: Fail retrieving info by column name if the column name is duplicated

resources/run_adf.sh
In order to upgrade mongohouse to `go1.22`, its dependencies must also be upgraded to 1.22. In this PR, I'm upgrading the go vesrion from 1.20 -> 1.22. Both versions exist in the evergreen toolchain so no concerns about unavailability there.
=> MHOUSE-10606: Upgrade to go1.22

.evg.yml
The issue was that the shell type was not specified on the Evergreen task and we used a specific Bash syntax.
Here is a task which I ran in a debug branch with the tag debug0.0.0 which work:
https://spruce.mongodb.com/task/mongo_jdbc_driver_test_version_from_tag_release_release_smoke__debug0.0.0_24_04_11_23_36_00/logs?execution=0
=> SQL-1953: Fix the build script to update the json feed correctly

build.gradle, src/main/java/com/mongodb/jdbc/oidc/OidcAuthFlow.java, src/main/java/com/mongodb/jdbc/oidc/TestOidcAuthFlowAndRefresh.java
This can be run using:
```
./gradlew  runAuthFlowAndRefresh
```
The actual `doRefresh` logic to be reviewed is in[ this commit](https://github.com/mongodb/mongo-jdbc-driver/commit/c3db95fb6c8138f8fe221ebc3b9d5b0f6b21d3e6).  The other functionality for `doAuthCodeFlow()` is in another PR SQL-1940. 
I'll update the branch it is based on to master when SQL-1940 is merged.
=> SQL-1941: Add doRefresh for OIDC authentication

src/main/java/com/mongodb/jdbc/MongoConnection.java, src/test/java/com/mongodb/jdbc/MongoConnectionTest.java
I tested with an older version of DBeaver and a newer version.
The driver works with both versions with this change. It fails as described when using an older driver with the newer DBeaver.
=> SQL-2049: Make all commit related logic no-op and report auto-commit = true instead of false.

resources/run_adf.sh
Adding in logic to mongohouse to route queries using the resource manager is causing the test `TestJDBCMongoSQL` to fail ([see patch here](https://spruce.mongodb.com/task/mongohouse_amazon2_test_e2e_mongosqljdbc_patch_9283efb893e5d345655761a64665f40c3c35b9e2_662a6fc68c3dfe0007a208a2_24_04_25_14_59_24?execution=0&sortBy=STATUS&sortDir=ASC)). Nothing evident from logs why it's failing but I'm fairly confident it's because we need to update the config used to run adf from [`frontend-agent-backend.yaml`](https://github.com/10gen/mongohouse/blob/master/testdata/config/inline_local/frontend-agent-backend.yaml) to [`frontend-agent-backend-crm.yaml`](https://github.com/10gen/mongohouse/blob/master/testdata/config/inline_local/frontend-agent-backend-crm.yaml). The configs are the same, except the …
=> SQL-2063: Update run-adf script to use updated config with CRM

resources/run_adf.sh
We're changing references to  the resource manager in ADF from acronyms `CRM`/`RM` to the full name, see [MHOUSE-11099](https://github.com/10gen/mongohouse/pull/9795). This includes config names so the referenced inline local file used by the SQL team also needs to be updated. This is necessary until the work in [MHOUSE-11063](https://jira.mongodb.org/browse/MHOUSE-11063) is done.
=> MHOUSE-11099: Update `run-adf.sh` inline local adf config name

.evg.yml, build.gradle, gradle.properties
Successful run: https://spruce.mongodb.com/task/mongo_jdbc_driver_code_quality_and_correctness_sbom_patch_65d75db0c5e89aab2d87ef90e67a3e0d12571c74_666375a3d3b2b1000758d666_24_06_07_21_03_39/logs?execution=0
SBOM created: https://evg-bucket-mongo-jdbc-driver.s3.amazonaws.com/artifacts/666375a3d3b2b1000758d666/code-quality-and-correctness/ssdlc/mongo-jdbc-driver.cdx.json
=> SQL-2091: Add SBOM Lite for JDBC

.evg.yml
Since the releases are created by gradle plugins, testing the tracing seems to be pretty complicated, so we've decided to skip the testing for now. At release time, we will adjust/fix if necessary.
=> SQL-2105: Trace JDBC releases using the Papertrail service

.evg.yml, gradle.properties
I changed the naming of things a little bit to be more consistent with what was done here https://github.com/10gen/sqlproxy/pull/460. 
Successful task and augmented SBOM can be seen here: https://spruce.mongodb.com/task/mongo_jdbc_driver_release_ssdlc_artifacts_patch_55092b1f39209c99237670c784a7d33d217edebb_6671e342268d4f0007bff51a_24_06_18_19_43_01/logs?execution=0
=> SQL-2098: Integrate JDBC vulnerability scanning (Silk)

.evg.yml
Adding a workaround for the `gradlew` command hanging on the Amazon Linux 2 host.  
The script would hang on the gradlew integration test, luckily it would output the `BUILD SUCCESS` or `BUILD FAILURE` status.  So I made the change to run the process in the background and check for one of those outputs.  Otherwise it times out with a failure.  
Here's an example of it correctly detecting a failure ([link](https://spruce.mongodb.com/task/mongo_jdbc_driver_amazon2_arm64_jdk_11_test_integration_patch_401a6ed19cf39e7b37a178f305ae5989a17d2680_66aaa69cc8b94100076e28ed_24_07_31_21_03_36/logs?execution=0&sortBy=STATUS&sortDir=ASC)).
=> SQL-2248: Fix integration test hang on amazon2-arm64 host

.evg.yml, src/integration-test/java/com/mongodb/jdbc/integration/MongoIntegrationTest.java, src/main/java/com/mongodb/jdbc/MongoDriver.java
This PR adds an integration test for a `mongodb+srv` style uri. For now, I'm using the `nathan` user but will talk to Alexi today about creating a new dedicated test user on her cluster.
Also, for now I have it expecting the exception that is thrown since Atlas does not natively support the SQL commands. I put a TODO to update it when we eventually implement support. The test will also start failing when we implement support, so the TODO is almost redundant.
This took a while since I initially investigated using the AWS Secret Manager, but it was not as easy as the wiki page implied (the wiki makes reference to scripts without links so it's unclear which scripts they're talking about or what they're supposed to do). Instead, I opted to use evergreen as our secret manager like we do for …
=> SQL-2286: Test mongodb+srv style connection string

.evg.yml, build.gradle, src/main/java/com/mongodb/jdbc/MongoDriver.java, src/test/java/com/mongodb/jdbc/MongoSQLTranslateLibTest.java, src/test/java/com/mongodb/jdbc/MongosqlLibTest.java
Loads library with name `libmongosqltranslate` from the same directory as where the Driver is located.  If that is not found it then loads from the path specified by the `MONGOSQL_TRANSLATE_PATH` env variable.  
I added a JNI test that I was using to confirm it was working, and added the library itself built on Ubuntu x86.  
If the library cannot be loaded, the `mongoSqlTranslateLibraryLoaded` variable will be false.  This can be checked in future implementations that intend to use the library and can at that point error out and report that the library is not loaded. 
```
use jni::JNIEnv;
use jni::objects::{JClass, JString};
use jni::sys::jstring;
#[no_mangle]
pub extern "system" fn Java_com_mongodb_jdbc_MongosqlLibTest_runCommand(
mut env: JNIEnv,
_class: JClass,
input: JString,
) -> …
```
=> SQL-2292: Load mongosqltranslate library if found

.evg.yml, resources/start_local_mdb.sh, src/integration-test/java/com/mongodb/jdbc/integration/ADFIntegrationTest.java, src/integration-test/java/com/mongodb/jdbc/integration/DCIntegrationTest.java, src/integration-test/java/com/mongodb/jdbc/integration/testharness/TestGenerator.java, src/main/java/com/mongodb/jdbc/BuildInfo.java, src/main/java/com/mongodb/jdbc/MongoConnection.java
This PR updates `MongoConnection` to use a `buildInfo` command instead of a `SELECT 1` query to test the connection, and to determine and store the cluster type based on the `buildInfo` result. It also updates the integration tests to be split into `ADFIntegrationTest` and `DCIntegrationTest` (direct cluster), and adds tests demonstrating community server is disallowed but enterprise server is allowed. I'm still working out any kinks in the evergreen and script updates/additions so bear with me on those!
=> SQL-2293: Differentiate cluster type upon connection

.evg.yml, resources/run_adf.sh
Generates the github token for cloning mongohouse.  The token also has permissions for mongohouse dependencies ie mongoast, sqlproxy, bsonutil.  If `GITHUB_TOKEN` is set `run_adf.sh` will use that token, otherwise revert to the way git clone is done currently (in case user does have the ssh key on local system). 
Here's a [patch](https://spruce.mongodb.com/version/66dc88eda92a3900071e48f5/tasks?page=0&sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC&variant=%5Eubuntu2204-64-jdk-8%24) with the github token change, it was run on a host with the ssh key removed that the devprod team provided to test the changes.
+    run_on: DEVPROD-5742-ubuntu2204-small
When approved I'll add similar changes to the other repos that need it: mongo-odbc-driver, mongo-powerbi-connector
=> SQL-2299: Use github token for cloning instead of ssh

src/main/java/com/mongodb/jdbc/MongoDatabaseMetaData.java, src/main/java/com/mongodb/jdbc/mongosql/MongoSQLTranslate.java
Added a function that formats the collection schema from `__sql_schemas` in a similar way to sqlGetSchemas and use that for direct cluster mode when processing column metadata.  Seemed most straightforward way with how the existing logic is, processing each collection. 
Tested manually against mongod using the `com.mongodb.jdbc.demo` package
```
ResultSet db_rs = dbm.getColumns("build", "%", "testcol", "%");
printResultSet(db_rs);
ResultSet row_rs = dbm.getBestRowIdentifier("build", null, "testcol", 0, true);
printResultSet(row_rs);
```
Output for getSchema():
```
{"schema": {"jsonSchema": {"bsonType": "object", "properties": {"_id": {"bsonType": "objectId"}, "a": {"bsonType": "int"}}, "required": ["_id", "a"], "additionalProperties": false}}, "ok": 1}
```
Output for printResultSet():
``` …
```
=> SQL-2375: Implement column metadata logic for Direct Cluster

.evg.yml
Note all the s3 put changes -- see [DEVPROD-6958](https://jira.mongodb.org/browse/DEVPROD-6958) for context. All of these have been failing for as long as we have evergreen history on this project (eg see [this](https://spruce.mongodb.com/task/mongo_jdbc_driver_amazon2_arm64_jdk_11_build_670aa4089b0a9b0008a950e0_24_10_12_16_30_00/logs?execution=0) run).
[Here](https://spruce.mongodb.com/task/mongo_jdbc_driver_amazon2_arm64_jdk_11_build_patch_85ef3aa7a1eb6cc96f9dda3f1a175ae32ca775c5_670d9414dbe83d00074a371c_24_10_14_21_58_56/logs?execution=0) is a successful build run showing the eap jar with the correct name as an artifact.
=> SQL-2397: evergreen updates

.evg.yml, build.gradle
If the property "isTagTriggered" is set, then:
- The release version (jar names) is the abbreviated git version. For example "3.0.0-alpha-libv1.0.0-alpha".
- The driver version (reported by the driver) is also the abbreviated git version.
If the property "isTagTriggered" is not set, then:
- The release version (jar names) is the abbreviated git version followed by `-SNAPSHOT`. For example "3.0.0-alpha-libv1.0.0-alpha-SNAPSHOT".
- The driver version (reported by the driver) is the full git version. For example "3.0.0-alpha-libv1.0.0-alpha-2-gbe21c46-dirty".
=> SQL-2437:  Set release version

src/main/java/com/mongodb/jdbc/BuildInfo.java, src/main/java/com/mongodb/jdbc/DataLake.java, src/main/java/com/mongodb/jdbc/MongoConnection.java, src/main/java/com/mongodb/jdbc/MongoDatabaseMetaData.java
We now correctly report the major and minor version. I've also updated it to work a bit better with adf version info, and report both adf version and mongosql version. Sample log output of internals:
```sh
[2024-11-06 13:19:23.453] [INFO] [c-2] com.mongodb.jdbc.MongoConnection initConnectionLogger: Connecting using MongoDB Atlas SQL interface JDBC Driver 3.0.0-alpha-libv1.0.0-alpha-11-g56f9799-dirty
[2024-11-06 13:19:25.355] [FINE] [c-2] com.mongodb.jdbc.MongoConnection determineClusterType: BuildInfo{version='7.2.0.v20241030.1.5.1', modules=null, ok=1, dataLake=DataLake{version='v20241030', mongoSQLVersion=1.5.1}}
[2024-11-06 13:19:25.356] [INFO] [c-2] com.mongodb.jdbc.MongoConnection$ConnValidation call: Connecting to cluster type AtlasDataFederation with server version …
```
=> SQL-2423: correctly report db version

.evg.yml
Split the `export variables` into two commands.  The first command has `silent: false` sets the variables that are generated and then echo's them.  The second command will get those variables as expansions and exports the rest of the variables.  
Let me know if there are more (or fewer) variables that you'd like added to the first command. 
Example of the variables being [logged](https://evergreen.mongodb.com/task_log_raw/mongo_jdbc_driver_eap_release_build_patch_6a76451cd6b0675fb82a87b301e19e70f3e62f45_6733916f2bc09500079c8023_24_11_12_17_33_38/0?type=T#L20).
=> SQL-2436: Split variables intialization for JDBC

src/main/java/com/mongodb/jdbc/MongoDatabaseMetaData.java, src/main/java/com/mongodb/jdbc/SortableBsonDocument.java
This PR filters out non-integer indexes. At first, I tried to set `ASC_OR_DESC` to null for non-integer indexes as [the spec](https://download.oracle.com/otn_hosted_doc/jdeveloper/905/jdbc-javadoc/oracle/jdbc/OracleDatabaseMetaData.html#getIndexInfo(java.lang.String,%20java.lang.String,%20java.lang.String,%20boolean,%20boolean)) says, "`ASC_OR_DESC String => column sort sequence, "A" => ascending, "D" => descending, may be null if sort sequence is not supported`". However, I then got the following DBeaver error: `Error reading table indexes: SQL Error: java.lang.IllegalArgumentException: The value for key ASC_OR_DESC can not be null`. So in the end, I filtered out all the non-integer indexes which works fine.
=> SQL-2460: Add handling for non-integer indexes

src/main/java/com/mongodb/jdbc/oidc/OidcAuthFlow.java
Updated how a browser is invoked to open the URL. 
This fixes an issue on Mac where OIDC authentication was failing when desktop operations could not be executed. 
Tested OIDC authentication on Mac and Windows against `sqlenginesoidctest-lxonw.a.query.mongodb-dev.net` using Tableau.
=> SQL-2506: Update browser invocation method for different platforms

src/integration-test/java/com/mongodb/jdbc/integration/DCIntegrationTest.java, src/main/java/com/mongodb/jdbc/MongoDriver.java
Added change to detect when a `MongoSecurityException` is hit in `connect()` to return SQLSTATE 28000 and an updated error message that authentication failed. 
Tested in Tableau and the error dialogue reports `Invalid username or password` as expected.  
Steps are in their [QA doc](https://tableau.github.io/connector-plugin-sdk/docs/manual-test#test-your-connector-with-tableau-desktop) under the section "Connect to the correct database with the wrong credentials".
Here's the output with the changes in this PR:
=> SQL-2514: Report authentication failure and expected SQLSTATE

.evg.yml, build.gradle, resources/third_party_header.txt
The file is copied in `META-INF/licenses`.
Merge check passed before cleaning  : https://spruce.mongodb.com/task/mongo_jdbc_driver_eap_release_build_patch_4b1bd9a6f9c32002e1cba7e78f655a2eba7da14c_679d6f3c0e788400079daf21_25_02_01_00_47_58/logs?execution=0
=> SQL-2534: Add THIRDPARTY-LICENSE notice

.evg.yml
This shows that if there is no tag, then the renaming happens: https://spruce.mongodb.com/task/mongo_jdbc_driver_release_build_patch_0d6972d2d8cffb9da601f998d7303816970af416_67edd161edd63400073c8ce5_25_04_03_00_08_09/logs?execution=0
Hopefully, all will be good this time when the release is done!
=> SQL-2538: Renaming build artifacts is only necessary for snapshot builds

.evg.yml, build.gradle
Because we make changes on the repo after cloning to generate the THIRDPARTY license file before building, we cannot rely on the Git version to know if the build is a release build.
We have to keep setting a Gradle variable.
I tried using environment variable and read them directly from the gradle script, but it doesn't pick it up.
I also didn't want to update the gradlew script to use an environment variable to magically add a Graddle property, because magic is hard to maintain.
I added the property to every call to gradlew to be safe.
=> SQL-2538: Fix release version logic

src/main/java/com/mongodb/jdbc/MongoResultSetMetaData.java, src/test/java/com/mongodb/jdbc/MongoResultSetMetaDataTest.java
Initially only `null` was being checked.  The empty selectOrder also is an empty list, added a check for that.
=> SQL-2732: Correct handling of empty select order list

src/main/java/com/mongodb/jdbc/MongoResultSetMetaData.java, src/test/java/com/mongodb/jdbc/MongoResultSetMetaDataTest.java
Cherry-picking commit from `on-prem-eap` to `master`
=> SQL-2732: Correct handling of empty select order list (#345)

src/main/java/com/mongodb/jdbc/MongoStatement.java, src/test/java/com/mongodb/jdbc/MongoStatementTest.java
Based on user PR https://github.com/mongodb/mongo-jdbc-driver/pull/355.
=> SQL-2833:  Guard MongoStatement#setFetchSize against invalid arguments - Signed commit

src/main/java/com/mongodb/jdbc/oidc/OidcAuthFlow.java
Adding `openid` and `offline_access` by default.  If `clientID + "/.default"` is in the requested scopes will add that as well.  
Verified that it works with our Okta test instance `mongodb://sqlenginesoidctest-lxonw.a.query.mongodb-dev.net` and an Azure idp instance.
=> SQL-2850: JDBC OIDC default scope improvement

gradle/publish.gradle
The sbom artifact can't be found during the publish step.  This could be due to the gradle upgrade, but not certain. 
Failure patch:
https://spruce.mongodb.com/task/mongo_jdbc_driver_release_publish_maven__v3.0.2_libv1.0.0_25_09_23_22_46_43/logs?execution=1
This change comments out the artifact lines to continue with jdbc release.
=> SQL-2965: Remove artifact declarations in publishing to continue release
